export const SKILLS = [
  { id: "nose", name: "Чувствительность носа", color: "#3a7aa8" },
  { id: "mix", name: "Техника смешивания", color: "#a84a3a" },
  { id: "notes", name: "Знание нот", color: "#4a8a4a" },
  { id: "analysis", name: "Анализ ароматов", color: "#7a5aa0" }
];

export const ZONES = [
  {
    id: "gweonid",
    name: "Лес Гвинедар",
    map: "assets/maps/gweonid.jpg",
    bg: "assets/world/hub.jpg",
    x: 52,
    y: 32,
    blurb: "Северные леса Нуа, где Консорциум Синей Соли учит читать воздух так же внимательно, как свиток."
  },
  {
    id: "solzreed",
    name: "Полуостров Солрид",
    map: "assets/maps/solzreed.jpg",
    bg: "assets/world/lavender.jpg",
    x: 69,
    y: 38,
    blurb: "Восточный полуостров: лавандовые гряды, фермы и ночная стража Хоупфорда."
  },
  {
    id: "lilyut",
    name: "Холмы Лилиот",
    map: "assets/maps/lilyut.png",
    bg: "assets/world/lilyut.jpg",
    x: 61,
    y: 32,
    blurb: "Тихие холмы между Гвинедаром и Солридом. Виндлоу стоит у воды; Земля говорящих камней лежит южнее и к этим берегам не относится."
  },
  {
    id: "seachild",
    name: "Пристань Сичайлд",
    map: "assets/maps/seachild.jpg",
    bg: "assets/world/sea-town.jpg",
    x: 55,
    y: 62,
    blurb: "Туманный причал у Двух Корон: краны, прилавки и два портала, между которыми пахнет смолой и солью."
  },
  {
    id: "stars",
    name: "Полуостров Падающих Звёзд",
    map: "assets/maps/stars.jpg",
    bg: "assets/world/star-light.jpg",
    x: 66,
    y: 56,
    blurb: "Южный берег Нуа: башня над обрывом, мосты и ветер, который срывает верхние ноты раньше, чем их успевают записать."
  },
  {
    id: "speaking",
    name: "Земля говорящих камней",
    map: "assets/maps/speaking.jpg",
    bg: "assets/world/stone-plaza.jpg",
    x: 48,
    y: 46,
    blurb: "Южнее Гвинедара камни держат свет. Здесь пещеры с колбами и площадь, где древо светится само."
  }
];

export const LOCATIONS = [
  {
    id: "hub",
    name: "Лесной приют",
    zone: "gweonid",
    region: "Гвинедар",
    bg: "assets/world/hub.jpg",
    blurb: "Лагерь гильдии среди старых берёз: здесь выдают поручения и ведут счёт эссенциям.",
    x: 22,
    y: 48,
    views: ["journal", "character"]
  },
  {
    id: "grove",
    name: "Роща духов",
    zone: "gweonid",
    region: "Долина духов",
    bg: "assets/world/spirit-grove.jpg",
    blurb: "Туман и светящиеся кроны. Сюда приходят с дневником, когда нужно слушать лес, а не полку.",
    x: 36,
    y: 22,
    views: ["diary"]
  },
  {
    id: "atelier",
    name: "Ателье алхимика",
    zone: "gweonid",
    region: "Хозяин Леса",
    bg: "assets/world/atelier.jpg",
    blurb: "Верстак, кристаллы и ряды флаконов. Здесь рождаются первые пробники.",
    x: 48,
    y: 52,
    views: ["craft"]
  },
  {
    id: "tower",
    name: "Башня травника",
    zone: "gweonid",
    region: "Беспокойная роща",
    bg: "assets/world/tower.jpg",
    blurb: "Камень, талисманы и полки с сырьём: каталог нот, который гильдия бережёт для учеников.",
    x: 70,
    y: 62,
    views: ["nose"]
  },
  {
    id: "plaza",
    name: "Площадь статуи",
    zone: "gweonid",
    region: "Старый двор",
    bg: "assets/world/grove-circle.jpg",
    blurb: "Каменный круг в роще. Сюда несут чужие флаконы, чтобы разобрать их по слоям.",
    x: 78,
    y: 38,
    views: ["analysis"]
  },
  {
    id: "warehouse",
    name: "Склад Ку-рара",
    zone: "gweonid",
    region: "Лесной дозор",
    bg: "assets/world/daru-auction.jpg",
    blurb: "Ку-рара, дару, стережёт полки с маслами и сундук гильдии. Здесь торгуются за эссенции и смотрят, каких банок не хватает.",
    x: 28,
    y: 72,
    views: ["chest"]
  },
  {
    id: "workshop",
    name: "Навес реторты",
    zone: "gweonid",
    region: "Хозяин Леса",
    bg: "assets/world/alchemy-tent.jpg",
    blurb: "Стол под красным пологом: колбы, весы и пипетки. После смены стол приводят к тишине.",
    x: 54,
    y: 70,
    views: ["craft"]
  },
  {
    id: "lavender",
    name: "Лавандовые поля",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/lavender.jpg",
    blurb: "Живые ряды лаванды. Сюда приходят нюхать сырьё, а не повторять чужие описания.",
    x: 48,
    y: 42,
    views: ["nose"]
  },
  {
    id: "solgate",
    name: "Врата Хоупфорда",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/solgate.jpg",
    blurb: "Ночной портал стражи. Отсюда в Гвинедар уходят обозы с цитрусом.",
    x: 68,
    y: 30,
    views: ["diary"]
  },
  {
    id: "farm",
    name: "Ферма Солрида",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/canyon.jpg",
    blurb: "Камень, вода и простой этюд. Здесь учат собирать аромат, не заглядывая в книгу гильдии.",
    x: 36,
    y: 58,
    views: ["craft"]
  },
  {
    id: "watch",
    name: "Сторожевая вышка",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/solrid-coast.jpg",
    blurb: "Ветер с моря. С вышки ясно слышно, чем берег пахнет после дождя.",
    x: 58,
    y: 70,
    views: ["diary"]
  },
  {
    id: "lilyut-shore",
    name: "Озеро Лилиот",
    zone: "lilyut",
    region: "Лилиот",
    bg: "assets/world/lilyut.jpg",
    blurb: "Серебряные кроны и тихая вода. Сюда приходят за коротким, честным наблюдением.",
    x: 29,
    y: 49,
    views: ["diary", "nose"]
  },
  {
    id: "relief",
    name: "Каменный рельеф",
    zone: "lilyut",
    region: "Лилиот",
    bg: "assets/world/relief.jpg",
    blurb: "Старая плита и фиолетовые цветы у её подножия. Здесь разбирают чужие флаконы без суеты площади.",
    x: 64,
    y: 44,
    views: ["analysis"]
  },
  {
    id: "windlow",
    name: "Виндлоу, пюпитр",
    zone: "lilyut",
    region: "Виндлоу",
    bg: "assets/world/windlow-room.jpg",
    blurb: "Открытая книга, перо и розовое кольцо. Гильдия просит прочесть том вживую и унести конспект своими словами.",
    x: 36,
    y: 57,
    views: ["book"]
  },
  {
    id: "crystals",
    name: "Кристальная поляна",
    zone: "gweonid",
    region: "Долина духов",
    bg: "assets/world/crystals.jpg",
    blurb: "Свет поднимается из земли, воздух холоден. Сюда приходят открывать ноты, которых ещё не касались.",
    x: 42,
    y: 36,
    views: ["nose"]
  },
  {
    id: "artisan",
    name: "Двор ремесленника",
    zone: "gweonid",
    region: "Старый двор",
    bg: "assets/world/forest-stall.jpg",
    blurb: "Навес среди гигантских листьев. Когда ателье занято, пробник собирают здесь.",
    x: 64,
    y: 44,
    views: ["craft"]
  },
  {
    id: "portal",
    name: "Ночной портал",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/mirage-portal.jpg",
    blurb: "Синий свет лежит на дороге. Здесь легко понять, чем ночь пахнет иначе, чем день.",
    x: 74,
    y: 48,
    views: ["diary"]
  },
  {
    id: "bench",
    name: "Скамья у воды",
    zone: "lilyut",
    region: "Лилиот",
    bg: "assets/world/bench.jpg",
    blurb: "Тихая вода и камень. Сюда садятся, когда нос устал от книг Виндлоу.",
    x: 40,
    y: 68,
    views: ["diary"]
  },
  {
    id: "oasis",
    name: "Оазис Солрида",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/oasis.jpg",
    blurb: "Тихая вода среди пальм. Здесь собирают этюд, который пахнет жаждой и тенью, а не лавандой с гряд.",
    x: 28,
    y: 48,
    views: ["craft", "diary"]
  },
  {
    id: "nuui",
    name: "Статуя Нууи",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/nuui-statue.jpg",
    blurb: "Каменная жрица в песке. Сюда несут ладан и пыль, а не цитрус с обозов.",
    x: 44,
    y: 26,
    views: ["craft"]
  },
  {
    id: "peaks",
    name: "Две скалы",
    zone: "lilyut",
    region: "Лилиот",
    bg: "assets/world/twin-peaks.jpg",
    blurb: "Два каменных зуба над елями. Воздух здесь холоднее, чем у озера.",
    x: 76,
    y: 30,
    views: ["craft", "diary"]
  },
  {
    id: "rose-thicket",
    name: "Розовый куст",
    zone: "gweonid",
    region: "Долина духов",
    bg: "assets/world/rose-bush.jpg",
    blurb: "Живой куст в траве рощи. Роза здесь пахнет листом и соком, а не мылом с полки.",
    x: 58,
    y: 28,
    views: ["craft", "nose"]
  },
  {
    id: "hill-fair",
    name: "Ярмарка на холме",
    zone: "lilyut",
    region: "Лилиот",
    bg: "assets/world/hill-market.jpg",
    blurb: "Навес, стол и дару у кромки холмов. Здесь учат собирать аромат, который слышно сквозь еду и ткань.",
    x: 52,
    y: 38,
    views: ["craft"]
  },
  {
    id: "garden-gate",
    name: "Цветы у врат",
    zone: "gweonid",
    region: "Старый двор",
    bg: "assets/world/garden-portal.jpg",
    blurb: "Горшки у светящейся двери. Цветок в глине пахнет иначе, чем тот же цветок в роще.",
    x: 72,
    y: 48,
    views: ["craft"]
  },
  {
    id: "sol-yard",
    name: "Двор с бочками",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-yard.jpg",
    blurb: "Соломенная крыша, бочки и гусь у арки. Здесь пахнет зерном, деревом и двором, а не лавандовой грядой.",
    x: 18,
    y: 66,
    views: ["craft", "diary"]
  },
  {
    id: "sol-table",
    name: "Стол у окна",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-table.jpg",
    blurb: "Длинный стол, пирог и зелень в горшках. Дом Солрида пахнет едой и мокрым деревом пола.",
    x: 22,
    y: 28,
    views: ["craft", "diary"]
  },
  {
    id: "sol-chest",
    name: "Сундук у окна",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-chest.jpg",
    blurb: "Сундук, цветок и вид на холмы. Тихая комната, где запах дерева сильнее поля за стеклом.",
    x: 34,
    y: 18,
    views: ["diary"]
  },
  {
    id: "sol-bed",
    name: "Спальня с пологом",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-bed.jpg",
    blurb: "Резное дерево, красный полог и подушки. Здесь учат тихий домашний шлейф.",
    x: 16,
    y: 48,
    views: ["craft"]
  },
  {
    id: "sol-balcony",
    name: "Балкон усадьбы",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-balcony.jpg",
    blurb: "Горшки с цветами над полем. Ветер с балкона мешает верхние ноты с сырой землёй.",
    x: 82,
    y: 58,
    views: ["craft", "nose"]
  },
  {
    id: "sol-hall",
    name: "Зал очага",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-hall.jpg",
    blurb: "Ковёр, шкура и длинный стол. Дым очага садится в дерево стен.",
    x: 74,
    y: 76,
    views: ["craft", "diary"]
  },
  {
    id: "sol-library",
    name: "Библиотека усадьбы",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-library.jpg",
    blurb: "Красный ковёр и полки до потолка. Бумага здесь теплее, чем в Виндлоу: рядом кровать и окно на горы.",
    x: 58,
    y: 16,
    views: ["diary", "book"]
  },
  {
    id: "sol-hills",
    name: "Дорога по холмам",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-hills.jpg",
    blurb: "Зелёные холмы, изгородь и дальний лес. Открытый Солрид без лавандовых гряд.",
    x: 46,
    y: 84,
    views: ["diary"]
  },
  {
    id: "sol-brook",
    name: "Ручей у дома",
    zone: "solzreed",
    region: "Солрид",
    bg: "assets/world/sol-brook.jpg",
    blurb: "Дом у воды и мокрые камни. Солрид здесь пахнет ручьём, а не морем с вышки.",
    x: 30,
    y: 78,
    views: ["diary", "nose"]
  },
  {
    id: "sea-town",
    name: "Туманная пристань",
    zone: "seachild",
    region: "Сичайлд",
    bg: "assets/world/sea-town.jpg",
    blurb: "Башни, краны и красные полотнища в тумане. Пристань пахнет смолой, сырым камнем и дымом.",
    x: 48,
    y: 42,
    views: ["diary", "craft"]
  },
  {
    id: "sea-gate",
    name: "Врата с гербом",
    zone: "seachild",
    region: "Сичайлд",
    bg: "assets/world/sea-gate.jpg",
    blurb: "Каменная арка и дару у прилавка. Отсюда в город входят с солью на плаще.",
    x: 28,
    y: 30,
    views: ["diary"]
  },
  {
    id: "sea-portals",
    name: "Два портала",
    zone: "seachild",
    region: "Сичайлд",
    bg: "assets/world/sea-portals.jpg",
    blurb: "Синяя и алая двери рядом. Воздух между ними холодный и сладковатый, как озон после грозы.",
    x: 72,
    y: 28,
    views: ["diary", "analysis"]
  },
  {
    id: "sea-market",
    name: "Мостовая рынка",
    zone: "seachild",
    region: "Сичайлд",
    bg: "assets/world/sea-market.jpg",
    blurb: "Булыжник, навесы и ряды склянок. Здесь аромат должен перекричать толпу.",
    x: 36,
    y: 68,
    views: ["craft"]
  },
  {
    id: "sea-stall",
    name: "Лавка склянок",
    zone: "seachild",
    region: "Сичайлд",
    bg: "assets/world/sea-stall.jpg",
    blurb: "Прилавок с зельями и цветами. Дару торгуется громче, чем пахнут флаконы.",
    x: 66,
    y: 64,
    views: ["craft", "nose"]
  },
  {
    id: "star-light",
    name: "Башня над морем",
    zone: "stars",
    region: "Падающие звёзды",
    bg: "assets/world/star-light.jpg",
    blurb: "Обрыв, море и высокая башня. Ветер снимает верхние ноты, база остаётся на камне.",
    x: 58,
    y: 36,
    views: ["diary", "craft"]
  },
  {
    id: "star-bridge",
    name: "Каменный мост",
    zone: "stars",
    region: "Падающие звёзды",
    bg: "assets/world/star-bridge.jpg",
    blurb: "Мост через зелёную лощину. С него слышно и траву, и дальнюю воду.",
    x: 32,
    y: 58,
    views: ["diary"]
  },
  {
    id: "star-cliff",
    name: "Дорога по обрыву",
    zone: "stars",
    region: "Падающие звёзды",
    bg: "assets/world/star-cliff.jpg",
    blurb: "Серая лента дороги между скал. Пыль, хвоя и пустой воздух.",
    x: 70,
    y: 52,
    views: ["diary", "nose"]
  },
  {
    id: "star-well",
    name: "Площадь с фонтаном",
    zone: "stars",
    region: "Падающие звёзды",
    bg: "assets/world/star-well.jpg",
    blurb: "Фонтан, дерево и мостовая. Городской камень пахнет иначе, чем берег.",
    x: 26,
    y: 32,
    views: ["diary", "craft"]
  },
  {
    id: "star-camp",
    name: "Повозка у сакуры",
    zone: "stars",
    region: "Падающие звёзды",
    bg: "assets/world/star-camp.jpg",
    blurb: "Синий полог, бочки и цветущее дерево. Привал пахнет тканью, вином и лепестками.",
    x: 64,
    y: 72,
    views: ["craft"]
  },
  {
    id: "star-beach",
    name: "Песчаный берег",
    zone: "stars",
    region: "Падающие звёзды",
    bg: "assets/world/star-beach.jpg",
    blurb: "Песок, сосны и тихая вода. Соль здесь мягче, чем у вышки Хоупфорда.",
    x: 40,
    y: 22,
    views: ["nose", "diary"]
  },
  {
    id: "stone-plaza",
    name: "Площадь светящегося древа",
    zone: "speaking",
    region: "Говорящие камни",
    bg: "assets/world/stone-plaza.jpg",
    blurb: "Круг камней и древо, которое светится без фонаря. Воздух сладкий и холодный.",
    x: 50,
    y: 44,
    views: ["craft", "diary"]
  },
  {
    id: "stone-door",
    name: "Вход с фонариками",
    zone: "speaking",
    region: "Говорящие камни",
    bg: "assets/world/stone-door.jpg",
    blurb: "Лестница в скалу и бумажные фонари. Порог пахнет воском и мокрым мхом.",
    x: 24,
    y: 30,
    views: ["diary"]
  },
  {
    id: "stone-cave",
    name: "Стол в пещере",
    zone: "speaking",
    region: "Говорящие камни",
    bg: "assets/world/stone-cave.jpg",
    blurb: "Зелёные кристаллы, колбы и фонари. Здесь собирают этюд, который светится даже в темноте.",
    x: 34,
    y: 66,
    views: ["craft"]
  },
  {
    id: "stone-shelf",
    name: "Полки склянок",
    zone: "speaking",
    region: "Говорящие камни",
    bg: "assets/world/stone-shelf.jpg",
    blurb: "Белые флаконы на корне дерева. Полка пахнет стеклом, спиртом и лесом за спиной.",
    x: 70,
    y: 58,
    views: ["craft", "nose"]
  },
  {
    id: "stone-totem",
    name: "Каменные лики",
    zone: "speaking",
    region: "Говорящие камни",
    bg: "assets/world/stone-totem.jpg",
    blurb: "Три лика и котёл между ними. Камень здесь холоднее, чем в роще Гвинедара.",
    x: 22,
    y: 50,
    views: ["diary", "analysis"]
  },
  {
    id: "stone-circle",
    name: "Круг у воды",
    zone: "speaking",
    region: "Говорящие камни",
    bg: "assets/world/stone-circle.jpg",
    blurb: "Камни кольцом среди берёз. Сюда приходят слушать, а не торговаться.",
    x: 58,
    y: 74,
    views: ["diary"]
  },
  {
    id: "stone-lilies",
    name: "Светящиеся лилии",
    zone: "speaking",
    region: "Говорящие камни",
    bg: "assets/world/stone-lilies.jpg",
    blurb: "Поле лилий, которые светятся у корня. Запах тонкий: вода, пыльца и ночь.",
    x: 76,
    y: 34,
    views: ["nose", "craft"]
  },
  {
    id: "stone-pond",
    name: "Пруд у скал",
    zone: "speaking",
    region: "Говорящие камни",
    bg: "assets/world/stone-pond.jpg",
    blurb: "Узкая вода между камней и красные шляпки грибов. Сырость держит базу дольше, чем ветер.",
    x: 42,
    y: 24,
    views: ["diary", "nose"]
  }
];

export const INGREDIENTS = [
  {
    id: "bergamot",
    name: "Бергамот",
    family: "Цитрус",
    layer: "Верхняя",
    loc: "lavender",
    hint: "Горький чай Эрл Грей, зелёная цедра, лёгкая цветочная пыль."
  },
  {
    id: "lemon",
    name: "Лимон",
    family: "Цитрус",
    layer: "Верхняя",
    loc: "lavender",
    hint: "Кислая цедра и сок: чистый удар, без апельсиновой сладости."
  },
  {
    id: "orange",
    name: "Сладкий апельсин",
    family: "Цитрус",
    layer: "Верхняя",
    loc: "lavender",
    hint: "Мякоть, цедра, солнечная сладость без горечи."
  },
  {
    id: "lavender",
    name: "Лаванда",
    family: "Травы",
    layer: "Верхняя / сердце",
    loc: "lavender",
    hint: "Камфорная свежесть, сухая трава, чистый лён, лёгкий мёд."
  },
  {
    id: "geranium",
    name: "Герань",
    family: "Цветы",
    layer: "Сердце",
    loc: "tower",
    hint: "Роза с зелёным стеблем, лимонная пыль, металлическая свежесть."
  },
  {
    id: "rose",
    name: "Роза",
    family: "Цветы",
    layer: "Сердце",
    loc: "tower",
    hint: "Лепесток, мёд, лёгкий чай, иногда лимонная кислота в абсолюте."
  },
  {
    id: "jasmine",
    name: "Жасмин",
    family: "Цветы",
    layer: "Сердце",
    loc: "tower",
    hint: "Белый цветок ночью, индол, спелый фрукт, тёплое масло."
  },
  {
    id: "ylang",
    name: "Иланг-иланг",
    family: "Цветы",
    layer: "Сердце",
    loc: "tower",
    hint: "Банановый крем, жасмин, резина, сладкий тропический цветок."
  },
  {
    id: "neroli",
    name: "Нероли",
    family: "Цветы",
    layer: "Сердце",
    loc: "lavender",
    hint: "Цветок апельсина, мёд, зелень, чистая вода после дождя."
  },
  {
    id: "petitgrain",
    name: "Петигрен",
    family: "Зелень",
    layer: "Верхняя",
    loc: "lavender",
    hint: "Горький лист апельсина, дерево, зелёная горечь без сока."
  },
  {
    id: "cedar",
    name: "Кедр",
    family: "Дерево",
    layer: "База",
    loc: "grove",
    hint: "Карандаш, сухая стружка, шкаф, тёплый лес без смолы сосны."
  },
  {
    id: "sandal",
    name: "Сандал",
    family: "Дерево",
    layer: "База",
    loc: "grove",
    hint: "Молоко, крем, мягкое дерево, тёплый бальзам."
  },
  {
    id: "vetiver",
    name: "Ветивер",
    family: "Дерево / земля",
    layer: "База",
    loc: "grove",
    hint: "Влажный корень, дым, земля после дождя, горький графит."
  },
  {
    id: "patchouli",
    name: "Пачули",
    family: "Земля",
    layer: "База",
    loc: "grove",
    hint: "Влажный погреб, какао, тёмная зелень, сладкая земля."
  },
  {
    id: "pine",
    name: "Пихта",
    family: "Хвоя",
    layer: "Верхняя / сердце",
    loc: "grove",
    hint: "Хвоя, смола и холодный воздух: зелень остаётся на пальцах."
  },
  {
    id: "oakmoss",
    name: "Дубовый мох",
    family: "Мох",
    layer: "База",
    loc: "grove",
    hint: "Влажный лес, лишайник, кожа, горькая зелень у корней."
  },
  {
    id: "vanilla",
    name: "Ваниль",
    family: "Бальзам",
    layer: "База",
    loc: "tower",
    hint: "Стручок, а не сахар: тёплый бальзам, дерево и сухая сладость."
  },
  {
    id: "benzoin",
    name: "Бензоин",
    family: "Бальзам",
    layer: "База",
    loc: "tower",
    hint: "Ваниль с ладаном, пластилин, тёплая смола, сахарная кора."
  },
  {
    id: "musk",
    name: "Белый мускус",
    family: "Мускус",
    layer: "База",
    loc: "atelier",
    hint: "Чистое бельё, тёплая кожа, воздух после стирки, мягкий шлейф."
  },
  {
    id: "iris",
    name: "Ирис",
    family: "Пудра",
    layer: "Сердце / база",
    loc: "lilyut-shore",
    hint: "Фиолетовый корень, пудра, морковь, сухой шёлк."
  },
  {
    id: "hay",
    name: "Сено",
    family: "Травы",
    layer: "Сердце",
    loc: "farm",
    hint: "Сухое поле, кумарин, сладкая пыль после косьбы."
  }
];

export const RECIPES = [
  {
    id: "free",
    name: "Свой этюд",
    chapter: "Глава. Свой путь",
    labor: 10,
    drops: null,
    lore: "Напиши название смеси своими словами и запиши её. Плюсы и капли не нужны."
  },
  {
    id: "lavender-water",
    name: "Роса Солрида",
    chapter: "Глава 1. Первые флаконы",
    labor: 12,
    drops: { lavender: 4, bergamot: 3, geranium: 2, cedar: 1 },
    lore: "Полевой одеколон стражи Солрида. Десять капель на пробник: смешай на спирте или в дипропиленгликоле и понюхай с бумаги."
  },
  {
    id: "citrus-splash",
    name: "Утро Гвинедаля",
    chapter: "Глава 1. Первые флаконы",
    labor: 10,
    drops: { lemon: 3, bergamot: 3, petitgrain: 2, neroli: 2 },
    lore: "Лёгкий цитрус для дневной бумаги. На кожу не лей сразу: сначала блоттер, потом запястье."
  },
  {
    id: "rose-chypre",
    name: "Шипр Беспокойной рощи",
    chapter: "Глава 2. Сердце и база",
    labor: 18,
    drops: { rose: 3, bergamot: 3, patchouli: 2, oakmoss: 2 },
    lore: "Классическая пирамида: цитрус сверху, роза в сердце, мох и пачули в основании. Дай смеси постоять час."
  },
  {
    id: "forest-vetiver",
    name: "Корень Хозяина Леса",
    chapter: "Глава 2. Сердце и база",
    labor: 16,
    drops: { vetiver: 3, cedar: 3, pine: 2, bergamot: 2 },
    lore: "Лесной этюд: ветивер тянет вниз, пихта держит воздух. Запиши, как запах меняется через два часа."
  },
  {
    id: "vanilla-amber",
    name: "Янтарь Ку-рара",
    chapter: "Глава 3. Шлейф",
    labor: 14,
    drops: { vanilla: 3, benzoin: 3, sandal: 3, orange: 1 },
    lore: "Тёплый бальзам с нижней полки Ку-рара. Капля апельсина только открывает базу; ванилью смесь не топи."
  },
  {
    id: "night-jasmine",
    name: "Ночь у врат",
    chapter: "Глава 3. Шлейф",
    labor: 20,
    drops: { jasmine: 4, ylang: 2, sandal: 2, musk: 2 },
    lore: "Белый цветок на сандале. Иланг легко перебивает остальные ноты — две капли, не больше."
  }
];

export const QUESTS = [
  {
    id: "diary-one",
    chapter: "Лес Гвинедар",
    title: "Страница в парфюмерном дневнике",
    npc: "Ясмин, летописец",
    text: "В роще духов бумага хранит запах дольше памяти. Сделай одну запись: что нюхал, где стоял и как воздух переменился через десять минут.",
    xp: 7,
    ess: 2,
    coins: 1,
    skill: "notes",
    skillXp: 14,
    loc: "grove",
    img: "assets/quests/diary-one.jpg",
    need: { diary: 1 }
  },
  {
    id: "clean-desk",
    chapter: "Лес Гвинедар",
    title: "Порядок на столе алхимика",
    npc: "Ку-рара, кладовщик-дару",
    text: "Ку-рара — дару, он сторожит склад гильдии. Просит прибрать стол после ночной смены: протереть пипетки спиртом, сложить бумагу и закрыть флаконы. Когда стол перестанет пахнуть вчерашним пачули, нажми «Стол прибран».",
    xp: 6,
    ess: 1,
    coins: 1,
    skill: "mix",
    skillXp: 7,
    loc: "workshop",
    img: "assets/quests/clean-desk.jpg",
    need: { clean: 1 }
  },
  {
    id: "grove-woods",
    chapter: "Лес Гвинедар",
    title: "Хвоя и мох у Хозяина Леса",
    npc: "Казим, травник Консорциума",
    text: "Пихта и дубовый мох — голос Гвинедара. Понюхай обе ноты в роще и запиши, чем лес отличается от солридских полей.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "nose",
    skillXp: 14,
    loc: "grove",
    img: "assets/quests/grove-woods.jpg",
    need: { groveSmell: 2 }
  },
  {
    id: "blue-salt-letter",
    chapter: "Лес Гвинедар",
    title: "Письмо Консорциуму Синей Соли",
    npc: "Ясмин, летописец",
    text: "Консорциум Синей Соли ждёт одну страницу из приюта. Напиши три вещи: чем сегодня пахнет лагерь, каких масел не хватает на складе и почему Ку-рара думает, что эссенции разбавляют водой. Запасы тают быстрее, чем их тратят ученики — вот в чём подозрение.",
    xp: 11,
    ess: 3,
    coins: 2,
    skill: "notes",
    skillXp: 14,
    loc: "hub",
    img: "assets/quests/blue-salt-letter.jpg",
    need: { letter: 1 }
  },
  {
    id: "daru-deal",
    chapter: "Лес Гвинедар",
    title: "Торг с Ку-рара",
    npc: "Ку-рара, кладовщик-дару",
    text: "Ку-рара — дару. Эссенции он отдаёт только после торга: сначала заламывает цену, потом шутит и сдаётся. Поговори с ним у полок, запиши, за сколько монет или услуг он отдаст мешок, и принеси запись гильдии.",
    xp: 10,
    ess: 3,
    coins: 2,
    skill: "analysis",
    skillXp: 12,
    loc: "warehouse",
    img: "assets/quests/daru-deal.jpg",
    need: { deal: 1 }
  },
  {
    id: "mix-one",
    chapter: "Лес Гвинедар",
    title: "Смешать пробную композицию",
    npc: "Энот, ретортчик",
    text: "Открой «Создать» и запиши смесь. Для своего этюда достаточно названия — плюсы не обязательны. После записи поручение сразу засчитают.",
    xp: 14,
    ess: 5,
    coins: 2,
    skill: "mix",
    skillXp: 19,
    loc: "atelier",
    img: "assets/quests/mix-one.jpg",
    need: { craft: 1 }
  },
  {
    id: "study-note",
    chapter: "Лес Гвинедар",
    title: "Изучить новую ноту",
    npc: "Казим, травник Консорциума",
    text: "В башне травника стоит сырьё, которого ты ещё не касался. Открой флакон, подержи его у бумаги и закрой. Затем сравни ощущение с записью гильдии.",
    xp: 12,
    ess: 4,
    coins: 1,
    skill: "notes",
    skillXp: 17,
    loc: "tower",
    img: "assets/quests/study-note.jpg",
    need: { newNote: 1 }
  },
  {
    id: "skin-wait",
    chapter: "Лес Гвинедар",
    title: "Проверить аромат на коже",
    npc: "Ясмин, летописец",
    text: "На бумаге аромат держится ровно, на коже живёт иначе. Нанеси пробник на запястье и через два часа допиши, что от него осталось.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "analysis",
    skillXp: 17,
    loc: "plaza",
    img: "assets/quests/skin-wait.jpg",
    need: { skin: 1 }
  },
  {
    id: "pyramid",
    chapter: "Лес Гвинедар",
    title: "Разобрать чужой аромат на пирамиду",
    npc: "Энот, ретортчик",
    text: "Возьми любой готовый флакон и разложи его на верх, сердце и базу. Название не угадывай: пиши лишь то, что слышишь.",
    xp: 12,
    ess: 4,
    coins: 2,
    skill: "analysis",
    skillXp: 19,
    loc: "plaza",
    img: "assets/quests/pyramid.jpg",
    need: { pyramid: 1 }
  },
  {
    id: "crystal-note",
    chapter: "Лес Гвинедар",
    title: "Нота на кристальной поляне",
    npc: "Казим, травник Консорциума",
    text: "У кристаллов воздух холоднее, чем в башне. Открой здесь незнакомый флакон и запиши, чем запах отличается от полки травника.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "nose",
    skillXp: 14,
    loc: "crystals",
    img: "assets/quests/crystal-note.jpg",
    need: { newNote: 1 }
  },
  {
    id: "artisan-mix",
    chapter: "Лес Гвинедар",
    title: "Пробник во дворе ремесленника",
    npc: "Энот, ретортчик",
    text: "Ателье занято сменами. Собери пробник под открытым небом и запиши, мешает ветер работе или, напротив, помогает ей.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 17,
    loc: "artisan",
    img: "assets/quests/artisan-mix.jpg",
    need: { craft: 1 }
  },
  {
    id: "smell-three",
    chapter: "Полуостров Солрид",
    title: "Три ноты на лавандовых полях",
    npc: "Казим, травник Консорциума",
    text: "На лавандовых полях Солрида сырьё пахнет иначе, чем в книгах гильдии. Понюхай три компонента и запиши то, что чувствуешь сам, а не то, что велено запомнить.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "nose",
    skillXp: 17,
    loc: "lavender",
    img: "assets/quests/smell-three.jpg",
    need: { smell: 3 }
  },
  {
    id: "sol-sea",
    chapter: "Полуостров Солрид",
    title: "Запах берега у вышки",
    npc: "Страж Хоупфорда",
    text: "После дождя Солрид пахнет иначе, чем Гвинедар. Встань на вышке и запиши, что сильнее — соль, трава или дым с фермы.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "notes",
    skillXp: 12,
    loc: "watch",
    img: "assets/quests/sol-sea.jpg",
    need: { diaryTag: "watch" }
  },
  {
    id: "hay-field",
    chapter: "Полуостров Солрид",
    title: "Сено на ферме Солрида",
    npc: "Страж Хоупфорда",
    text: "После косьбы поле пахнет сладкой пылью. Понюхай сено на ферме и запиши, чем оно отличается от лаванды на соседних грядах.",
    xp: 8,
    ess: 2,
    coins: 1,
    skill: "nose",
    skillXp: 12,
    loc: "farm",
    img: "assets/quests/hay-field.jpg",
    need: { smell: 1 }
  },
  {
    id: "solgate-night",
    chapter: "Полуостров Солрид",
    title: "Ночь у врат Хоупфорда",
    npc: "Страж Хоупфорда",
    text: "У врат ночью слышны стража, лошади и цитрус с обозов. Запиши, чем пахнет это место, пока ещё горят факелы.",
    xp: 8,
    ess: 2,
    coins: 1,
    skill: "notes",
    skillXp: 12,
    loc: "solgate",
    img: "assets/quests/solgate-night.jpg",
    need: { diaryTag: "solgate" }
  },
  {
    id: "portal-glow",
    chapter: "Полуостров Солрид",
    title: "Наблюдение у ночного портала",
    npc: "Ясмин, летописец",
    text: "Синий свет меняет то, как нос читает воздух. Постой у портала и запиши, чем ночь отличается от дневного поля.",
    xp: 8,
    ess: 3,
    coins: 1,
    skill: "notes",
    skillXp: 12,
    loc: "portal",
    img: "assets/quests/portal-glow.jpg",
    need: { diaryTag: "portal" }
  },
  {
    id: "windlow-book",
    chapter: "Холмы Лилиот",
    title: "Том в доме Виндлоу",
    npc: "Хранитель пюпитра",
    text: "В Виндлоу лежит том, который гильдия не выносит из дома. Прочти главу вживую — о нотах, пирамиде или истории духов — и законспектируй своими словами. Поручение большое и сдаётся лишь однажды.",
    xp: 34,
    ess: 12,
    coins: 8,
    skill: "notes",
    skillXp: 34,
    loc: "windlow",
    img: "assets/quests/windlow-book.jpg",
    need: { book: 1 },
    once: true
  },
  {
    id: "lilyut-walk",
    chapter: "Холмы Лилиот",
    title: "Наблюдение у озера Лилиот",
    npc: "Ясмин, летописец",
    text: "После Виндлоу нос устаёт от бумаги. Выйди к озеру и запиши, чем воздух холмов отличается от рощи Гвинедара. Это не Земля говорящих камней: берега путать не стоит.",
    xp: 8,
    ess: 2,
    coins: 1,
    skill: "notes",
    skillXp: 12,
    loc: "lilyut-shore",
    img: "assets/quests/lilyut-walk.jpg",
    need: { diaryTag: "lilyut-shore" }
  },
  {
    id: "iris-shore",
    chapter: "Холмы Лилиот",
    title: "Ирис у озера",
    npc: "Казим, травник Консорциума",
    text: "У воды Лилиота хранят корень ириса. Понюхай его здесь и запиши, что слышишь первым: пудру, морковь или сухой шёлк.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "nose",
    skillXp: 14,
    loc: "lilyut-shore",
    img: "assets/quests/iris-shore.jpg",
    need: { smell: 1 }
  },
  {
    id: "bench-water",
    chapter: "Холмы Лилиот",
    title: "Запись со скамьи у воды",
    npc: "Ясмин, летописец",
    text: "Сядь на скамью и не торопись. Одна спокойная запись — вода, камень, трава. Без сравнений с Марианополем: только холмы.",
    xp: 7,
    ess: 2,
    coins: 1,
    skill: "notes",
    skillXp: 10,
    loc: "bench",
    img: "assets/quests/bench-water.jpg",
    need: { diaryTag: "bench" }
  },
  {
    id: "relief-look",
    chapter: "Холмы Лилиот",
    title: "Разбор у каменного рельефа",
    npc: "Энот, ретортчик",
    text: "У плиты тише, чем на площади статуи. Возьми чужой флакон и разложи его на верх, сердце и базу. Пиши лишь то, что слышишь.",
    xp: 11,
    ess: 4,
    coins: 2,
    skill: "analysis",
    skillXp: 14,
    loc: "relief",
    img: "assets/quests/relief-look.jpg",
    need: { pyramid: 1 }
  },
  {
    id: "sol-yard-note",
    chapter: "Полуостров Солрид",
    title: "Двор с бочками",
    npc: "Страж Хоупфорда",
    text: "У соломенной крыши стоят бочки, гусь и круглая арка. Запиши, чем этот двор пахнет сильнее: зерном, мокрым деревом или птицей. Лаванду с гряд сюда не подмешивай.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "notes",
    skillXp: 12,
    loc: "sol-yard",
    img: "assets/world/sol-yard.jpg",
    need: { write: 1 }
  },
  {
    id: "sol-library-note",
    chapter: "Полуостров Солрид",
    title: "Полки усадьбы",
    npc: "Ясмин, летописец",
    text: "В библиотеке Солрида красный ковёр и книги до потолка. Это не Виндлоу. Запиши, чем здешняя бумага отличается от тома у озера: теплом комнаты, пылью или деревом кровати у окна.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "notes",
    skillXp: 12,
    loc: "sol-library",
    img: "assets/world/sol-library.jpg",
    need: { write: 1 }
  },
  {
    id: "sol-brook-note",
    chapter: "Полуостров Солрид",
    title: "Ручей под окном",
    npc: "Казим, травник Консорциума",
    text: "Дом стоит у узкой воды, за ним скалы. Понюхай берег и запиши, что слышишь первым: мох, сырой камень или дым из трубы.",
    xp: 9,
    ess: 2,
    coins: 1,
    skill: "nose",
    skillXp: 12,
    loc: "sol-brook",
    img: "assets/world/sol-brook.jpg",
    need: { write: 1 }
  },
  {
    id: "sea-fog",
    chapter: "Пристань Сичайлд",
    title: "Туман над пристанью",
    npc: "Смотритель пристани",
    text: "Башня с краном теряется в сером воздухе. Запиши три запаха пристани: камень, смола, дым. Если слышишь море — скажи, далеко ли оно.",
    xp: 11,
    ess: 3,
    coins: 2,
    skill: "notes",
    skillXp: 14,
    loc: "sea-town",
    img: "assets/world/sea-town.jpg",
    need: { write: 1 }
  },
  {
    id: "sea-trade",
    chapter: "Пристань Сичайлд",
    title: "Торг на мостовой",
    npc: "Ку-рара, кладовщик-дару",
    text: "На булыжнике стоят навесы и склянки. Ку-рара уже кричит цену. Запиши, чем пахнет рынок, когда толпа громче флаконов, и что ты не станешь покупать.",
    xp: 11,
    ess: 3,
    coins: 2,
    skill: "analysis",
    skillXp: 14,
    loc: "sea-market",
    img: "assets/world/sea-market.jpg",
    need: { write: 1 }
  },
  {
    id: "sea-doors",
    chapter: "Пристань Сичайлд",
    title: "Синяя и алая дверь",
    npc: "Ясмин, летописец",
    text: "Два портала стоят рядом. Постой между ними и запиши, чем синий свет пахнет иначе, чем алый. Не списывай с Хоупфорда: здесь другой камень.",
    xp: 12,
    ess: 4,
    coins: 2,
    skill: "analysis",
    skillXp: 14,
    loc: "sea-portals",
    img: "assets/world/sea-portals.jpg",
    need: { write: 1 }
  },
  {
    id: "star-tower",
    chapter: "Полуостров Падающих Звёзд",
    title: "Башня на обрыве",
    npc: "Хранитель башни",
    text: "Высокая башня смотрит на море с края скал. Запиши, что ветер уносит первым и что остаётся на камне, когда верхние ноты уже сняты.",
    xp: 11,
    ess: 3,
    coins: 2,
    skill: "notes",
    skillXp: 14,
    loc: "star-light",
    img: "assets/world/star-light.jpg",
    need: { write: 1 }
  },
  {
    id: "star-span",
    chapter: "Полуостров Падающих Звёзд",
    title: "Ветер на мосту",
    npc: "Ясмин, летописец",
    text: "С каменного моста видно лощину и дальнюю воду. Одна запись: трава снизу, камень перил, и есть ли в воздухе соль.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "notes",
    skillXp: 12,
    loc: "star-bridge",
    img: "assets/world/star-bridge.jpg",
    need: { write: 1 }
  },
  {
    id: "star-halt",
    chapter: "Полуостров Падающих Звёзд",
    title: "Привал у сакуры",
    npc: "Страж Хоупфорда",
    text: "Синий полог, бочки и цветущее дерево. Запиши привал так, чтобы в нём были и лепестки, и вино, и пыль дороги. Без лаванды Солрида.",
    xp: 10,
    ess: 3,
    coins: 2,
    skill: "nose",
    skillXp: 12,
    loc: "star-camp",
    img: "assets/world/star-camp.jpg",
    need: { write: 1 }
  },
  {
    id: "speak-tree",
    chapter: "Земля говорящих камней",
    title: "Древо на площади",
    npc: "Хранитель камней",
    text: "Посреди круга стоит древо и светится без огня. Запиши, чем площадь пахнет: холодным светом, грибами у тропы или мокрым камнем. Это не роща Гвинедара.",
    xp: 12,
    ess: 4,
    coins: 2,
    skill: "notes",
    skillXp: 14,
    loc: "stone-plaza",
    img: "assets/world/stone-plaza.jpg",
    need: { write: 1 }
  },
  {
    id: "speak-cave",
    chapter: "Земля говорящих камней",
    title: "Колбы при кристаллах",
    npc: "Казим, травник Консорциума",
    text: "В пещере стол, зелёные кристаллы и фонари. Понюхай воздух у колб и запиши, что сильнее: стекло, воск или сырой камень свода.",
    xp: 11,
    ess: 3,
    coins: 2,
    skill: "nose",
    skillXp: 14,
    loc: "stone-cave",
    img: "assets/world/stone-cave.jpg",
    need: { write: 1 }
  },
  {
    id: "speak-ring",
    chapter: "Земля говорящих камней",
    title: "Кольцо берёз",
    npc: "Ясмин, летописец",
    text: "Камни стоят кругом у воды, берёзы светлые. Одна спокойная запись: камень, лист, тишина. Без торга и без Марианополя.",
    xp: 10,
    ess: 3,
    coins: 1,
    skill: "notes",
    skillXp: 12,
    loc: "stone-circle",
    img: "assets/world/stone-circle.jpg",
    need: { write: 1 }
  },
  {
    id: "simple-own",
    chapter: "Свой путь",
    title: "Свой простой аромат",
    npc: "Энот, ретортчик",
    text: "Открой «Свой этюд», напиши название смеси — хоть «вербена и мелисса» — и нажми «Записать смесь». Капли и плюсы не нужны.",
    xp: 16,
    ess: 5,
    coins: 3,
    skill: "mix",
    skillXp: 21,
    loc: "farm",
    img: "assets/quests/own-simple-table.jpg",
    need: { freeCraft: 1 }
  },
  {
    id: "complex-own",
    chapter: "Свой путь",
    title: "Свой сложный аромат",
    npc: "Казим, травник Консорциума",
    text: "Напиши название сложного этюда и отметь «пять нот и больше». Формулу гильдия не подскажет. Плюсы не обязательны.",
    xp: 26,
    ess: 8,
    coins: 6,
    skill: "mix",
    skillXp: 29,
    loc: "atelier",
    img: "assets/quests/own-complex-jars.jpg",
    need: { complexCraft: 1 },
    once: true
  },
  {
    id: "own-simple-table",
    chapter: "Свой путь",
    title: "Простой этюд у алхимического стола",
    npc: "Энот, ретортчик",
    text: "Под красным пологом стоит стол с колбами. Открой «Свой этюд», напиши простое название — две-три ноты своими словами — и запиши смесь. Капли и плюсы не нужны.",
    xp: 16,
    ess: 5,
    coins: 3,
    skill: "mix",
    skillXp: 21,
    loc: "workshop",
    img: "assets/quests/own-simple-table.jpg",
    need: { freeCraft: 1 }
  },
  {
    id: "own-complex-jars",
    chapter: "Свой путь",
    title: "Сложный аромат у банок",
    npc: "Казим, травник Консорциума",
    text: "У весов и цветных банок собери сложный этюд: пять нот и больше. Напиши название смеси и отметь сложность. Формулу гильдия не подскажет.",
    xp: 26,
    ess: 8,
    coins: 6,
    skill: "mix",
    skillXp: 29,
    loc: "workshop",
    img: "assets/quests/own-complex-jars.jpg",
    need: { complexCraft: 1 },
    once: true
  },
  {
    id: "own-rose",
    chapter: "Свой путь",
    title: "Роза с опушки",
    npc: "Казим, травник Консорциума",
    text: "У куста в роще роза пахнет листом и соком, не мылом с полки. Собери этюд так, чтобы в нём остался живой куст, а не конфетка. Напиши название смеси и чем она отличается от гильдейской розы.",
    xp: 12,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "rose-thicket",
    img: "assets/quests/own-rose.jpg",
    need: { write: 1 }
  },
  {
    id: "own-nuui",
    chapter: "Свой путь",
    title: "Ладан у статуи Нууи",
    npc: "Жрица Нууи",
    text: "У каменной жрицы в песке просят не цветы, а тихий ладан: пыль, смола, тёплый камень. Придумай смесь, которой можно постоять у статуи, не перекрывая ветер пустыни. Запиши название и три ноты своими словами.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 18,
    loc: "nuui",
    img: "assets/quests/own-nuui.jpg",
    need: { write: 1 }
  },
  {
    id: "own-oasis",
    chapter: "Свой путь",
    title: "Вода оазиса",
    npc: "Страж Хоупфорда",
    text: "Пальма, сухая кора и стоячая вода пахнут иначе, чем лаванда с гряд. Собери этюд жажды: мокрый песок, тень, чуть зелени. Назови смесь так, чтобы стража поняла — это не морской одеколон.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "oasis",
    img: "assets/quests/own-oasis.jpg",
    need: { write: 1 }
  },
  {
    id: "own-mirage",
    chapter: "Свой путь",
    title: "Пробник для агента миража",
    npc: "Агент миража, дару-аукционист",
    text: "Дару у врат орёт про Мираж и просит пробник, который услышат сквозь пыль торга. Не делай дешёвую сладость: верх должен крикнуть, база — не свалиться через час. Напиши название и за сколько капель ты сам бы его купил.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 18,
    loc: "warehouse",
    img: "assets/quests/own-mirage.jpg",
    need: { write: 1 }
  },
  {
    id: "own-portal",
    chapter: "Свой путь",
    title: "Дыхание врат",
    npc: "Ясмин, летописец",
    text: "Синяя дверь пахнет озоном, металлом и ночью. Собери этюд портала: холод сверху, тёплый камень внизу. Название должно помнить свет, а не лаванду поля.",
    xp: 10,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "portal",
    img: "assets/quests/own-portal.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stall",
    chapter: "Свой путь",
    title: "Смесь под лесным навесом",
    npc: "Энот, ретортчик",
    text: "Под чёрным пологом среди гигантских листьев ветер таскает зелень прямо в колбу. Собери пробник на этом навесе и запиши, что сильнее — лист, сырое дерево или твой задуманный цветок. Утка рядом не считается нотой.",
    xp: 10,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "artisan",
    img: "assets/quests/own-stall.jpg",
    need: { write: 1 }
  },
  {
    id: "own-peaks",
    chapter: "Свой путь",
    title: "Воздух двух скал",
    npc: "Казим, травник Консорциума",
    text: "Между двумя каменными зубами воздух режет нос: хвоя, мокрый гранит, пустота. Собери горный этюд без сладкой базы. Напиши название и что ты убрал, чтобы смесь не стала «ёлкой из лавки».",
    xp: 12,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "peaks",
    img: "assets/quests/own-peaks.jpg",
    need: { write: 1 }
  },
  {
    id: "own-pots",
    chapter: "Свой путь",
    title: "Цветы у светящихся врат",
    npc: "Ясмин, летописец",
    text: "Горшки у двери пахнут землёй и поливом, а не дикой рощей. Собери этюд сада: глина, стебель, чуть портального холода сбоку. Назови смесь и скажи, какая нота у тебя из горшка, а какая — из света двери.",
    xp: 10,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "garden-gate",
    img: "assets/quests/own-pots.jpg",
    need: { write: 1 }
  },
  {
    id: "own-fair",
    chapter: "Свой путь",
    title: "Ярмарочный этюд",
    npc: "Ку-рара, кладовщик-дару",
    text: "На холме пахнет тканью навеса, едой со стола и чужими руками. Собери аромат, который выдержит ярмарку: не исчезнет рядом с пирогом и не перекричит дару. Запиши название и кого этим пробником ты хочешь остановить у прилавка.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "hill-fair",
    img: "assets/quests/own-fair.jpg",
    need: { write: 1 }
  },
  {
    id: "own-paper",
    chapter: "Свой путь",
    title: "Запах бумаги Виндлоу",
    npc: "Хранитель пюпитра",
    text: "В комнате с книгой пахнут бумага, перо, старое дерево и пыль кольца над пюпитром. Собери тихий этюд чтения: без крика цветов. Напиши название смеси и какую страницу она должна напоминать.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 18,
    loc: "windlow",
    img: "assets/quests/own-paper.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-yard",
    chapter: "Свой путь",
    title: "Этюд двора с бочками",
    npc: "Энот, ретортчик",
    text: "Собери свой этюд соломенного двора: зерно, мокрое дерево, чуть птичьего пера. Напиши название. Капли не нужны.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-yard",
    img: "assets/world/sol-yard.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-table",
    chapter: "Свой путь",
    title: "Этюд стола у окна",
    npc: "Энот, ретортчик",
    text: "На столе пирог, зелень и дальний холм за окном. Собери домашний этюд еды и дерева, без рыночной сладости. Напиши название смеси.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-table",
    img: "assets/world/sol-table.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-chest",
    chapter: "Свой путь",
    title: "Этюд сундука",
    npc: "Ясмин, летописец",
    text: "Сундук, цветок на тумбе и окно в поле. Собери тихий этюд закрытой комнаты: дерево, пыль ткани, один цветок. Название — своими словами.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-chest",
    img: "assets/world/sol-chest.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-bed",
    chapter: "Свой путь",
    title: "Этюд красного полога",
    npc: "Энот, ретортчик",
    text: "Полог, подушки и резное дерево. Собери шлейф спальни: ткань, тёплое дерево, чуть пыли. Без крика цветов. Напиши название.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-bed",
    img: "assets/world/sol-bed.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-balcony",
    chapter: "Свой путь",
    title: "Этюд балкона",
    npc: "Казим, травник Консорциума",
    text: "Горшки над полем. Собери этюд, где цветок в глине встречается с ветром холмов. Напиши название и какая нота с балкона, а какая — с поля.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-balcony",
    img: "assets/world/sol-balcony.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-hall",
    chapter: "Свой путь",
    title: "Этюд очага",
    npc: "Энот, ретортчик",
    text: "Зал с ковром и шкурой пахнет дымом и старым деревом. Собери вечерний этюд дома. Название должно помнить огонь, не лаванду.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-hall",
    img: "assets/world/sol-hall.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-library",
    chapter: "Свой путь",
    title: "Этюд красных полок",
    npc: "Хранитель пюпитра",
    text: "Полки, ковёр и окно на горы. Собери этюд чтения для усадьбы Солрида — не копию бумаги Виндлоу. Напиши название и какую полку он должен открывать.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-library",
    img: "assets/world/sol-library.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-hills",
    chapter: "Свой путь",
    title: "Этюд зелёных холмов",
    npc: "Казим, травник Консорциума",
    text: "Дорога идёт через луг к дальнему лесу. Собери этюд открытого поля: трава, тёплая пыль, чуть хвои на горизонте. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-hills",
    img: "assets/world/sol-hills.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sol-brook",
    chapter: "Свой путь",
    title: "Этюд ручья",
    npc: "Казим, травник Консорциума",
    text: "Вода у дома, камни и труба на крыше. Собери этюд сырого берега. Название — так, чтобы стража не спутала его с морем.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sol-brook",
    img: "assets/world/sol-brook.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sea-town",
    chapter: "Свой путь",
    title: "Этюд туманной пристани",
    npc: "Смотритель пристани",
    text: "Кран, башни и серый воздух. Собери этюд, который слышно сквозь туман: смола, мокрый камень, холодный дым. Напиши название.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sea-town",
    img: "assets/world/sea-town.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sea-gate",
    chapter: "Свой путь",
    title: "Этюд гербовых врат",
    npc: "Ясмин, летописец",
    text: "Арка с гербом и дару у входа. Собери короткий этюд порога: камень, железо, чужой плащ. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sea-gate",
    img: "assets/world/sea-gate.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sea-portals",
    chapter: "Свой путь",
    title: "Этюд двух дверей",
    npc: "Энот, ретортчик",
    text: "Синий портал и алый стоят парой. Собери этюд с холодным верхом и тёплой базой, чтобы оба света ужились в одном флаконе. Напиши название.",
    xp: 14,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 18,
    loc: "sea-portals",
    img: "assets/world/sea-portals.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sea-market",
    chapter: "Свой путь",
    title: "Этюд булыжного рынка",
    npc: "Ку-рара, кладовщик-дару",
    text: "Навесы на мостовой пахнут толпой и зельями. Собери смесь, которую услышат между прилавками. Напиши название и кого хочешь остановить.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sea-market",
    img: "assets/world/sea-market.jpg",
    need: { write: 1 }
  },
  {
    id: "own-sea-stall",
    chapter: "Свой путь",
    title: "Этюд лавки склянок",
    npc: "Энот, ретортчик",
    text: "На прилавке ряды флаконов и цветы. Собери свой пробник так, будто он уже стоит среди них, но не копирует чужую цену. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "sea-stall",
    img: "assets/world/sea-stall.jpg",
    need: { write: 1 }
  },
  {
    id: "own-star-light",
    chapter: "Свой путь",
    title: "Этюд башни над морем",
    npc: "Хранитель башни",
    text: "Обрыв, башня и серое море. Собери этюд, у которого ветер снимает верх, а камень держит базу. Напиши название.",
    xp: 14,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 18,
    loc: "star-light",
    img: "assets/world/star-light.jpg",
    need: { write: 1 }
  },
  {
    id: "own-star-bridge",
    chapter: "Свой путь",
    title: "Этюд каменного моста",
    npc: "Ясмин, летописец",
    text: "Мост над зелёной лощиной. Собери смесь травы снизу и пыли перил. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "star-bridge",
    img: "assets/world/star-bridge.jpg",
    need: { write: 1 }
  },
  {
    id: "own-star-cliff",
    chapter: "Свой путь",
    title: "Этюд обрыва",
    npc: "Казим, травник Консорциума",
    text: "Серая дорога между скал. Собери сухой этюд: пыль, хвоя, пустота. Сладкую базу убери. Напиши название и что выкинул.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "star-cliff",
    img: "assets/world/star-cliff.jpg",
    need: { write: 1 }
  },
  {
    id: "own-star-well",
    chapter: "Свой путь",
    title: "Этюд фонтана",
    npc: "Энот, ретортчик",
    text: "Площадь, дерево и чаша фонтана. Собери городской этюд мокрого камня и листвы. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "star-well",
    img: "assets/world/star-well.jpg",
    need: { write: 1 }
  },
  {
    id: "own-star-camp",
    chapter: "Свой путь",
    title: "Этюд синего полога",
    npc: "Страж Хоупфорда",
    text: "Повозка, бочки и розовое дерево. Собери этюд привала: ткань, вино, лепесток. Напиши название.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "star-camp",
    img: "assets/world/star-camp.jpg",
    need: { write: 1 }
  },
  {
    id: "own-star-beach",
    chapter: "Свой путь",
    title: "Этюд тихого берега",
    npc: "Казим, травник Консорциума",
    text: "Песок и сосны, вода без грохота прибоя. Собери мягкую соль, не одеколон Хоупфорда. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "star-beach",
    img: "assets/world/star-beach.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stone-plaza",
    chapter: "Свой путь",
    title: "Этюд светящегося древа",
    npc: "Хранитель камней",
    text: "Древо на площади светится само. Собери этюд холодного света и мокрого круга камней. Напиши название.",
    xp: 14,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 18,
    loc: "stone-plaza",
    img: "assets/world/stone-plaza.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stone-door",
    chapter: "Свой путь",
    title: "Этюд бумажных фонарей",
    npc: "Ясмин, летописец",
    text: "Лестница в скалу увешана фонарями. Собери этюд порога: воск, мох, тёплый свет в холодном камне. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "stone-door",
    img: "assets/world/stone-door.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stone-cave",
    chapter: "Свой путь",
    title: "Этюд пещерного стола",
    npc: "Казим, травник Консорциума",
    text: "У зелёных кристаллов стоят колбы. Собери свой сложный по смыслу этюд пещеры: стекло, воск, сырой свод. Напиши название. Плюсы не нужны.",
    xp: 14,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 18,
    loc: "stone-cave",
    img: "assets/world/stone-cave.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stone-shelf",
    chapter: "Свой путь",
    title: "Этюд белых флаконов",
    npc: "Энот, ретортчик",
    text: "Полка с белыми склянками вросла в корень. Собери этюд стекла и спирта, а лес оставь лёгким верхом. Напиши название.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "stone-shelf",
    img: "assets/world/stone-shelf.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stone-totem",
    chapter: "Свой путь",
    title: "Этюд каменных ликов",
    npc: "Хранитель камней",
    text: "Три лика и котёл. Собери холодный этюд камня без цветочной сладости. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "stone-totem",
    img: "assets/world/stone-totem.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stone-circle",
    chapter: "Свой путь",
    title: "Этюд круга у воды",
    npc: "Ясмин, летописец",
    text: "Берёзы и камни кольцом. Собери тихий этюд: лист, вода, холодный камень. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "stone-circle",
    img: "assets/world/stone-circle.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stone-lilies",
    chapter: "Свой путь",
    title: "Этюд светящихся лилий",
    npc: "Казим, травник Консорциума",
    text: "Лилии светятся у корня. Собери тонкий этюд пыльцы и ночной воды, чтобы он не стал духами с полки. Напиши название.",
    xp: 13,
    ess: 4,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "stone-lilies",
    img: "assets/world/stone-lilies.jpg",
    need: { write: 1 }
  },
  {
    id: "own-stone-pond",
    chapter: "Свой путь",
    title: "Этюд пруда у скал",
    npc: "Казим, травник Консорциума",
    text: "Узкая вода, камни и красные грибы. Собери сырой этюд, который держится дольше ветра. Напиши название.",
    xp: 12,
    ess: 3,
    coins: 2,
    skill: "mix",
    skillXp: 16,
    loc: "stone-pond",
    img: "assets/world/stone-pond.jpg",
    need: { write: 1 }
  },
  {
    id: "decode-maria",
    chapter: "Чужие города",
    title: "Раскрыть аромат из Марианополя",
    npc: "Ясмин, летописец",
    text: "Из Марианополя везут духи дороже соли. Возьми любой городской флакон и восстанови пирамиду: какие ноты, в каком слое и чего больше. С коробки не списывай.",
    xp: 21,
    ess: 6,
    coins: 4,
    skill: "analysis",
    skillXp: 23,
    loc: "relief",
    img: "assets/quests/decode-maria.jpg",
    need: { decode: 1 },
    once: true
  },
  {
    id: "decode-ost",
    chapter: "Чужие города",
    title: "Раскрыть аромат из Ост-Терры",
    npc: "Ку-рара, кладовщик-дару",
    text: "Ост-Терра пахнет иначе: морем, складом, чужими специями. Ку-рара уже нюхал такие флаконы и любит приврать. Разбери второй чужой аромат сам и запиши, чем он не похож на марианопольский.",
    xp: 21,
    ess: 6,
    coins: 4,
    skill: "analysis",
    skillXp: 23,
    loc: "plaza",
    img: "assets/quests/decode-ost.jpg",
    need: { decodeOst: 1 },
    once: true
  }
];

export const LOOT = [
  { kind: "skill", skill: "nose", amount: 15, label: "Капля росы — чувствительность носа" },
  { kind: "skill", skill: "mix", amount: 15, label: "Пыль реторты — техника смешивания" },
  { kind: "skill", skill: "notes", amount: 15, label: "Лист гербария — знание нот" },
  { kind: "skill", skill: "analysis", amount: 15, label: "Осколок кристалла — анализ" },
  { kind: "xp", amount: 48, label: "Свиток ученика — опыт" },
  { kind: "ess", amount: 20, label: "Мешочек эссенций" },
  { kind: "inspire", amount: 25, label: "Зелёный кристалл — вдохновение" },
  { kind: "coins", amount: 15, label: "Горсть монет Консорциума" }
];

export const CHAPTERS = [
  "Лес Гвинедар",
  "Полуостров Солрид",
  "Холмы Лилиот",
  "Пристань Сичайлд",
  "Полуостров Падающих Звёзд",
  "Земля говорящих камней",
  "Свой путь",
  "Чужие города"
];

export const RECIPE_CHAPTERS = [
  "Глава. Свой путь",
  "Глава 1. Первые флаконы",
  "Глава 2. Сердце и база",
  "Глава 3. Шлейф"
];
